inputs:
  - file: "data/file1.csv"
    type: "csv"
    key_columns: ["id"]
    transformations:
      - drop_duplicates:
          columns: ["id", "name"]
          keep: "first"
  - file: "data/file2.csv"
    type: "xlsx"
    sheet: "Sheet1"
    key_columns: ["id"]
    transformations:
      - drop_duplicates:
          columns: ["id"]
          keep: "last"

operation:
  type: "merge"
  how: "inner"

output:
  file: "data/output.csv"
  type: "csv"
  delimiter: ","

preprocessing:
  columns_to_standardize:
    - "id"
