# High-level settings for the entire process
settings:
  output_folder: "/Users/yuval/MetaMorphic/output/mock_first_run"
  output_file_name: "final_merge_file.csv"

# Define the input files
# Each entry has:
# - path: The actual file path
# - name: A reference name used internally for joins
# - keys: The columns that will serve as the join key(s)
# - (optional) transformations: Preprocessing steps like column selection or filtering
files:
  - name: "file3"
    path: "/Users/yuval/MetaMorphic/sampels/batch_1/file3.csv"
    transformations:
        - standardize_id_columns: ['id']
  - name: "file4"
    path: "/Users/yuval/MetaMorphic/sampels/batch_1/file4.csv"
    transformations:
      - standardize_id_columns: ['תעודת זהות']

  - name: "file5"
    path: "/Users/yuval/MetaMorphic/sampels/batch_1/file5.csv"
    transformations:
      - standardize_id_columns: ['id']

# Define how files relate to each other
# This can be a sequence of merges, each specifying:
# - source: The primary "base" dataset
# - join_with: The dataset to join onto it
# - join_type: Type of join (if not set, the default from settings will apply)
# - on: The join keys if not already inherited from the file definitions
joins:
  - source: "file3"
    join_with: "file4"
    join_type: "inner"
    join_on:
      - file3: "id"
      - file4: "תעודת זהות"
  
  - source: "file3" 
    join_with: "file5"
    join_type: "left"
    join_on: 
      - file3:
        - "id"
      - file5: 
        - "id"
