# High-level settings for the entire process
settings:
  output_folder: "/Users/yuval/MetaMorphic/output/real_data_1"
  output_file_name: "final_merge_file_new.xlsx"

# Define the input files
# Each entry has:
# - path: The actual file path
# - name: A reference name used internally for joins
# - keys: The columns that will serve as the join key(s)
# - (optional) transformations: Preprocessing steps like column selection or filtering
files:
  - name: "CAPS_before"
    path: '/Users/yuval/Documents/metamorphic_data/Questionnaires.xlsx'
    sheet: 'CAPS'
    transformations:
      - filter_rows:
          column: "שלב בטיפולים"
          operator: "is_in"
          values: ["לפני טיפול בתא לחץ"]   
  - name: "PTSD_partA_before"
    path: '/Users/yuval/Documents/metamorphic_data/Questionnaires.xlsx'
    sheet: 'PTSD_partA'
    transformations:
      - filter_rows:
          column: "אנא בחר/י את שלב הטיפולים בו את/ה נמצא/ת בעת מילוי השאלון"
          operator: "is_in"
          values: ['לפני טיפול ראשון בתא לחץ']
  
  - name: "PTSD_partB_before"
    path: '/Users/yuval/Documents/metamorphic_data/Questionnaires.xlsx'
    sheet: 'PTSD_partB'
    transformations:
      - filter_rows:
          column: "אנא בחר/י את שלב הטיפולים בו את/ה נמצא/ת בעת מילוי השאלון"
          operator: "is_in"
          values: ['לפני טיפול ראשון בתא לחץ']

  - name: "CAPS_after"
    path: '/Users/yuval/Documents/metamorphic_data/Questionnaires.xlsx'
    sheet: 'CAPS'
    transformations:
      - filter_rows:
          column: "שלב בטיפולים"
          operator: "is_in"
          values: ["אחרי טיפול בתא לחץ"]   
  - name: "PTSD_partA_after"
    path: '/Users/yuval/Documents/metamorphic_data/Questionnaires.xlsx'
    sheet: 'PTSD_partA'
    transformations:
      - filter_rows:
          column: "אנא בחר/י את שלב הטיפולים בו את/ה נמצא/ת בעת מילוי השאלון"
          operator: "is_in"
          values: ['לפני טיפול ראשון בתא לחץ']
  
  - name: "PTSD_partB_after"
    path: '/Users/yuval/Documents/metamorphic_data/Questionnaires.xlsx'
    sheet: 'PTSD_partB'
    transformations:
      - filter_rows:
          column: "אנא בחר/י את שלב הטיפולים בו את/ה נמצא/ת בעת מילוי השאלון"
          operator: "is_in"
          values: ['לפני טיפול ראשון בתא לחץ']

  - name: "COGNITIVE"
    path: '/Users/yuval/Downloads/PTSD 500 anonimized.xlsx'
    sheet: 'COGNITIVE'
    transformations:
      - select_columns : ["קוד סגול", "global score", "memory", "verbarl memory ", "delayed verbal memory", "non-verbal memory", "delayed non verbal", "executive functions", "attention", "information processiong speed", "motor skills", "global score-2", "memory-2", "verbarl memory -2", "delayed verbal memory-2", "non-verbal memory-2", "delayed non verbal-2", "executive functions-2", "attention-2", "information processiong speed-2", "motor skills-2"]
          
  



# Define how files relate to each other
# This can be a sequence of merges, each specifying:
# - source: The primary "base" dataset
# - join_with: The dataset to join onto it
# - join_type: Type of join (if not set, the default from settings will apply)
# - on: The join keys if not already inherited from the file definitions
joins:
  - type: "merge"
    source: "CAPS_before"
    join_with: "COGNITIVE"
    join_type: "left"
    join_on:
      - CAPS_before: "קוד מטופל (9 ספרות)"
      - COGNITIVE: 'קוד סגול' 

  - type: "merge"
    source: "CAPS_before"
    join_with: "PTSD_partA_before"
    join_type: "left"
    join_on:
      - CAPS_before: "קוד מטופל (9 ספרות)"
      - PTSD_partA_before: 'קוד אישי'
  
  - type: "merge"
    source: "CAPS_before"
    join_with: "PTSD_partB_before"
    join_type: "left"
    join_on:
      - CAPS_before: "קוד מטופל (9 ספרות)"
      - PTSD_partB_before: 'קוד אישי'    

  - type: "merge"
    source: "CAPS_after"
    join_with: "COGNITIVE"
    join_type: "left"
    join_on:
      - CAPS_after: "קוד מטופל (9 ספרות)"
      - COGNITIVE: 'קוד סגול' 

  - type: "merge"
    source: "CAPS_after"
    join_with: "PTSD_partA_after"
    join_type: "left"
    join_on:
      - CAPS_after: "קוד מטופל (9 ספרות)"
      - PTSD_partA_after: 'קוד אישי'
  
  - type: "merge"
    source: "CAPS_after"
    join_with: "PTSD_partB_after"
    join_type: "left"
    join_on:
      - CAPS_after: "קוד מטופל (9 ספרות)"
      - PTSD_partB_after: 'קוד אישי' 

  - type: "concat"
    dataframes: ["CAPS_before","CAPS_after"]
    output: "CAPS_all"

  # - source: "CAPS_before"
  #   join_with: "COGNITIVE_before"
  #   join_type: "left"
  #   join_on:
  #     - CAPS: "קוד מטופל (9 ספרות)"
  #     - COGNITIVE: 'קוד סגול'    
